//+_+_+_+_+_+_+__+__+__+__+__+_+_
//_+__+_By: "Sir" Arthur_+__+__+_
//+_+_+_+_+_+_+__+__+__+__+__+_+_

#include <iostream>
#include <conio.h>
#include <windows.h>
#include <stdlib.h>
using namespace std;
int main()
{
    system("cls");
    cout << "           ****\n";
    cout << "       ************\n";
    cout << "      ***************                                      *\n";
    cout << "      ***************\n";
    cout << "       *************\n";;
    cout << "           *****\n";
    Sleep(500);
    system("cls");
    cout << "           ****\n";
    cout << "       ************\n";
    cout << "      ***************                                *\n";
    cout << "      ***************\n";
    cout << "       *************\n";;
    cout << "           *****\n";
    Sleep(500);
    system("cls");
    cout << "           ****\n";
    cout << "       ************\n";
    cout << "      ***************\n";
    cout << "      ***************                          *\n";
    cout << "       *************\n";;
    cout << "           *****\n";
    Sleep(500);
    system("cls");
    cout << "           ****\n";
    cout << "       ************\n";
    cout << "      ***************                      *\n";
    cout << "      ***************\n";
    cout << "       *************\n";;
    cout << "           *****\n";
    Sleep(500);
    system("cls");
    cout << "           ****\n";
    cout << "       ************\n";
    cout << "      ***************\n";
    cout << "      ***************                  *\n";
    cout << "       *************\n";;
    cout << "           *****\n";
    Sleep(500);
    system("cls");
    cout << "           ****\n";
    cout << "       ************\n";
    cout << "      ***************              *\n";
    cout << "      ***************\n";
    cout << "       *************\n";;
    cout << "           *****\n";
    Sleep(500);
    system("cls");
    cout << "           ****\n";
    cout << "       ************\n";
    cout << "      ***************\n";
    cout << "      ***************          *\n";
    cout << "       *************\n";;
    cout << "           *****\n";
    Sleep(500);
    system("cls");
    cout << "           ****\n";
    cout << "       ************\n";
    cout << "      ***************      *\n";
    cout << "      ***************\n";
    cout << "       *************\n";;
    cout << "           *****\n";
    Sleep(500);
    system("cls");
    cout << "           ****\n";
    cout << "       ************\n";
    cout << "      ***************\n";
    cout << "      ***************  *\n";
    cout << "       *************\n";;
    cout << "           *****\n";
    Sleep(500);
    system("cls");
    cout << "           * ** *\n";
    cout << "       * ********** *\n";
    cout << "      * ************** *\n";
    cout << "      * ************* *\n";
    cout << "       * *********** *\n";;
    cout << "           * *** *\n";
    Sleep(500);
    system("cls");
    cout << "           * * * *\n";
    cout << "       * * ******** * *\n";
    cout << "      * * *********** * *\n";
    cout << "      * * *********** * *\n";
    cout << "       * * ********* * *\n";;
    cout << "           * * * * *\n";
    Sleep(500);
    system("cls");
    cout << "           * * * *\n";
    cout << "       * * * ****** * * *\n";
    cout << "      * * * ********* * * *\n";
    cout << "      * * * ********* * * *\n";
    cout << "       * * * ******* * * *\n";;
    cout << "           * * * * *\n";
    Sleep(500);
    system("cls");
    cout << "           **    *\n";
    cout << "       ****   **     **  *  **\n";
    cout << "      ***   *****    ***  ****\n";
    cout << "      **** **   **** ***    **\n";
    cout << "       *** ***      **  *****\n";;
    cout << "           ***  **\n";
    Sleep(500);
    system("cls");
    cout << "           **    **\n";
    cout << "       **   *   **     **  ***  **\n";
    cout << "      ***   ***   ****    **  *  **\n";
    cout << "      ****   ***    ****     **   *\n";
    cout << "       ****   ****     *****\n";;
    cout << "           **   **    *\n";
    Sleep(500);
    system("cls");
    cout << "             ********\n";
    cout << "            ****\n";
    cout << "                ****\n";
    cout << "                    ***\n";
    cout << "                *****\n";;
    cout << "              ****** \n";
    Sleep(500);
    system("cls");
    cout << "               *\n";
    cout << "                \n";
    cout << "               *\n";
    cout << "               *\n";
    cout << "               *\n";;
    cout << "               *\n";
    Sleep(500);
    system("cls");
    cout << "              ********\n";
    cout << "              ***  **\n";
    cout << "              *** **\n";
    cout << "              ** **\n";
    cout << "              **  **\n";;
    cout << "              **   **\n";
    Sleep(500);
    system("cls");
    cout << "             ********              *               ********            *********\n";
    cout << "            ****                                   ***  **\n";
    cout << "                ****               *               *** **\n";
    cout << "                    ***            *               ** **\n";
    cout << "                *****              *               **  **\n";;
    cout << "              ******               *               **   **\n";
    Sleep(1000);
    system("cls");
    for(int i = 1;i <= 10; i++){
    cout << "Carregado | ";
    Sleep(100);
    system("cls");
    cout << "Carregado / ";
    Sleep(100);
    system("cls");
    cout << "Carregado - ";
    Sleep(100);
    system("cls");
    cout << "Carregado | ";
    Sleep(100);
    system("cls");
    cout << "Carregado \ ";
    Sleep(100);
    system("cls");
    cout << "Carregado - ";
    Sleep(100);
    system("cls");
    }

return 0;
}
